import { downloadFile, request } from "./request.js";

export async function getOverview() { return request("/analytics/overview"); }
export async function getTopAspects(limit = 12) { return request(`/analytics/top_aspects?limit=${limit}`); }
export async function getAspectSentimentDistribution(limit = 12) { return request(`/analytics/aspect_sentiment_distribution?limit=${limit}`); }
export async function getTrends(interval = "day") { return request(`/analytics/trends?interval=${interval}`); }
export async function getDashboardKpis(filters = {}) { const p = new URLSearchParams(); if (filters.from) p.set("from", filters.from); if (filters.to) p.set("to", filters.to); if (filters.domain) p.set("domain", filters.domain); return request(`/analytics/dashboard_kpis${p.toString() ? `?${p}` : ""}`); }
export async function getAspectLeaderboard(limit = 25, domain = "") { const p = new URLSearchParams(); p.set("limit", String(limit)); if (domain) p.set("domain", domain); return request(`/analytics/aspect_leaderboard?${p.toString()}`); }
export async function getAspectTrends(interval = "day", domain = "", limit = 500) { const p = new URLSearchParams(); p.set("interval", interval); p.set("limit", String(limit)); if (domain) p.set("domain", domain); return request(`/analytics/aspect_trends?${p.toString()}`); }
export async function getEmergingAspects(interval = "day", lookbackBuckets = 7, domain = "") { const p = new URLSearchParams(); p.set("interval", interval); p.set("lookback_buckets", String(lookbackBuckets)); if (domain) p.set("domain", domain); return request(`/analytics/emerging_aspects?${p.toString()}`); }
export async function getEvidence(aspect = "", sentiment = "", limit = 50, domain = "") { const p = new URLSearchParams(); if (aspect) p.set("aspect", aspect); if (sentiment) p.set("sentiment", sentiment); p.set("limit", String(limit)); if (domain) p.set("domain", domain); return request(`/analytics/evidence?${p.toString()}`); }
export async function getAspectDetail(aspect, interval = "day", domain = "") { const p = new URLSearchParams(); p.set("interval", interval); if (domain) p.set("domain", domain); return request(`/analytics/aspect_detail/${encodeURIComponent(aspect)}?${p.toString()}`); }
export async function getAlerts(domain = "") { const q = domain ? `?domain=${encodeURIComponent(domain)}` : ""; return request(`/analytics/alerts${q}`); }
export async function getNeedsReview(limit = 100) { return request(`/analytics/needs_review?limit=${limit}`); }
export async function getNovelCandidates(limit = 100) { return request(`/analytics/novel_candidates?limit=${limit}`); }
export async function clearAlert(alertId) { return request(`/analytics/alerts/${alertId}`, { method: "DELETE" }); }
export async function getImpactMatrix(limit = 20, domain = "") { const p = new URLSearchParams(); p.set("limit", String(limit)); if (domain) p.set("domain", domain); return request(`/analytics/impact_matrix?${p.toString()}`); }
export async function getSegments(limit = 20, domain = "") { const p = new URLSearchParams(); p.set("limit", String(limit)); if (domain) p.set("domain", domain); return request(`/analytics/segments?${p.toString()}`); }
export async function getWeeklySummary(domain = "") { const q = domain ? `?domain=${encodeURIComponent(domain)}` : ""; return request(`/analytics/weekly_summary${q}`); }
export async function getUserReviewsSummary(domain = "") { const q = domain ? `?domain=${encodeURIComponent(domain)}` : ""; return request(`/analytics/user_reviews/summary${q}`); }
export async function getUserReviewsList({ domain = "", product_id = "", username = "", min_rating = "", max_rating = "", limit = 50, offset = 0 } = {}) { const p = new URLSearchParams(); if (domain) p.set("domain", domain); if (product_id) p.set("product_id", product_id); if (username) p.set("username", username); if (min_rating !== "") p.set("min_rating", String(min_rating)); if (max_rating !== "") p.set("max_rating", String(max_rating)); p.set("limit", String(limit)); p.set("offset", String(offset)); return request(`/analytics/user_reviews/list?${p.toString()}`); }
export async function getAdminExport(filters = {}) { const p = new URLSearchParams(); if (filters.domain) p.set("domain", filters.domain); if (filters.limit) p.set("limit", String(filters.limit)); if (filters.offset) p.set("offset", String(filters.offset)); return request(`/analytics/export/json${p.toString() ? `?${p.toString()}` : ""}`); }
export async function exportAdminJson(filters = {}) { const p = new URLSearchParams(); if (filters.domain) p.set("domain", filters.domain); if (filters.limit) p.set("limit", String(filters.limit)); if (filters.offset) p.set("offset", String(filters.offset)); return downloadFile(`/analytics/export/json${p.toString() ? `?${p.toString()}` : ""}`, "reviewop-admin-export.json"); }
export async function exportAdminPdf(filters = {}) { const p = new URLSearchParams(); if (filters.domain) p.set("domain", filters.domain); if (filters.limit) p.set("limit", String(filters.limit)); if (filters.offset) p.set("offset", String(filters.offset)); return downloadFile(`/analytics/export/pdf${p.toString() ? `?${p.toString()}` : ""}`, "reviewop-admin-export.pdf"); }
